
# ~~~~~~~ build ~~~~~~~~~~~~

FROM node:latest as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN npm install

COPY . /usr/src/app
RUN npm run build

# ~~~~~~ serve ~~~~~~~~~~~~

FROM nginx:latest

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
